modify link checker new

diff --git a/.github/workflows/Link_checker.yml b/.github/workflows/Link_checker.yml
--- a/.github/workflows/Link_checker.yml
+++ b/.github/workflows/Link_checker.yml
@@ -14,8 +14,34 @@ jobs:
         with:
           ref: gh-pages
 
-      - name: Install Markdown link checker
-        uses: lycheeverse/lychee-action@v1.2.0
-        with:
-          # Check links in Markdown files
-          args: --verbose --no-progress docs/devel/pages/*.html
+      - name: Check links
+        run: |
+          failure=false
+          # List all HTML files
+          html_files=$(find . -name "*.html")
+
+          # Loop through each HTML file
+          for file in $html_files; do
+            echo "Checking links in $file"
+          # Loop through each link not matching the pattern
+            for link in $other_links; do
+              # Check if the link starts with "http://" or "https://"
+              if [[ $link == http://* ]] || [[ $link == https://* ]]; then
+                # Check the return code of the HTTP link
+                status_code=$(curl -s -o /dev/null -w "%{http_code}" "$link")
+
+                if [ "$status_code" -eq 200 ] || [ "$status_code" -ge 300 ] && [ "$status_code" -lt 400 ]; then
+                  echo "    [✓] Link is valid: $link"
+                else
+                  echo "    [✖] Link is invalid: $link (HTTP $status_code)"
+                  failure=true
+                fi
+              fi
+            done
+          done || failure=true
+          
+          # Exit the workflow with a failure status if any failure occurred
+          if [ "$failure" = true ]; then
+            echo "Error: At least one link doesn't work"
+            exit 1
+          fi
